services:
  vue:
    build: 
      context: ./app
      dockerfile: Dockerfile
    container_name: ah-yapergo_web
    ports:
      - "9025:8080"
    command: sh -c "http-server dist" 

  db:
    image: mysql:latest
    container_name: ah-yapergo_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3315:3306"

  api:
    build: .
    container_name: ah-yapergo_api
    ports:
      - "8025:5000"
    volumes:
      - .:/code
    command: python app.py
  
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql_data:

#netwoks:
 # ah:
  #  external: true
