services:
#APP WEB
  vue:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ah-yapergo_web
    ports:
      - "9025:8080"
    command: sh -c "http-server dist" 
    environment:
      - VITE_API_BASE_URL=http://api:8000 
    networks:
      - ag

#BASE DE DATOS
  db:
    image: mysql:latest
    container_name: ah-yapergo_db
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: DB
      MYSQL_USER: root
      MYSQL_PASSWORD: admin1234
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3315:3306"
    networks:
      - ag

  api:
    build: ./backend/app
    container_name: ah-yapergo_api
    ports:
      - "8025:5000"
    volumes:
      - .:/code
    command: python app.py
  
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql_data:

networks:
  ag:
    external: true
