services:

  #BASE DE DATOS
  db:
    #Cambiar usuario y contraseña //Implementar ejecución de scripts
    image: mysql:latest
    container_name: ah-yapergo_db
    environment:
      MYSQL_ROOT_USER:  root
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: DB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/app/sql:/docker-entrypoint-initdb.d
    ports:
      - "3315:3306"
    networks:
      - ag

  #APP WEB - VUE
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    container_name: ah-yapergo_web
    ports:
      - "9025:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

    volumes:
      - ./frontend:/app # Volumen solo para la aplicación web
    #command: sh -c "http-server dist"
    networks:
      - ag

  #API - FASTAPI
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
      - URL_DATABASE=${URL_DATABASE}
    container_name: ah-yapergo_api
    ports:
      - "8025:8000"
    depends_on:
      - db
    environment:
      - URL_DATABASE=${URL_DATABASE} #cambiar ruta de la base de datos
      #- URL_DATABASE=mysql+pymysql://admin:admin1234@db:3306/DB #cambiar ruta de la base de datos
    volumes:
      - ./backend:/app
#    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
    command: ["./wait-for-it.sh", "db:3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - ag

  #ADMINER
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - ag

volumes:
  mysql_data:


networks:
  ag:
    #driver: bridge
    external: true
