version: "3.8"

services:
  vue:
    build: 
      context: ./app
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    command: sh -c "http-server dist" 

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  mysql_data:
